Add up to date check
cucumber/polyglot-release pull request #65
Opened 2022-05-13 23:57 UTC by mpkorstanje

### 🤔 What's changed?

Added a check to test if `polyglot-release` is up to date.

### ⚡️ What's your motivation? 

We're getting to the point where `polyglot-release` will not need many changes. This makes issues such as #64 easier to deal with by properly versioning `polyglot-release`.

However making a release with an out of date version of `polyglot-release` may botch the release. For example, a newly added language may not be released. By checking if `polyglot-release` is up to date we can avoid these problems.

### 🏷️ What kind of change is this?

- :zap: New feature (non-breaking change which adds new behaviour)

### ♻️ Anything particular you want feedback on?

The tests are a doozy.

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://cucumber.io/conduct/)
- [x] I've changed the behaviour of the code
  - [x] I have added/updated tests to cover my changes.
- [x] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly.
- [x] Users should know about my change
  - [x] I have added an entry to the "Unreleased" section of the [**CHANGELOG**](../CHANGELOG.md), linking to this pull request.

2022-05-14 00:10 UTC, mpkorstanje commented on CHANGELOG.md
> +- First release of polyglot-release
This change log isn't quite right, but we'll have to fix that after the first release of polyglot-release.

2022-05-14 02:52 UTC, mpkorstanje commented on polyglot-release-test
> +    /bin/bash "$test" \
`sh` doesn't support `pushd` and `popd` which are useful to have in tests too.

2022-05-15 00:53 UTC, mattwynne commented on polyglot-release-test
> +    /bin/bash "$test" \
👍

2022-05-15 00:53 UTC, mattwynne commented on polyglot-release-test
> +    /bin/bash "$test" \
Maybe mirror that in the manual test too?

2022-05-15 00:54 UTC, mattwynne commented on polyglot-release-test
> +    /bin/bash "$test" \
Ignore me; that one already uses bash

2022-05-15 01:20 UTC, mattwynne commented on polyglot-release-test
> +    POLYGLOT_RELEASE_GIT_REPO="$workdir/origin" \
This is only true for one of the test fixtures. I think it would be better to have this set somewhere else, like in the test `.sh` itself.

2022-05-15 01:20 UTC, mattwynne commented on polyglot-release
> +  if [[ ! -f README.md ]]; then
is this a likely edge-case we need to care about?

2022-05-15 01:20 UTC, mattwynne commented on polyglot-release
> +SUPPORTED_LANGUAGES+=("polyglot-release")
My initial reaction here is that I don't like seeing this one-off case in here; I worry that it will encourage others to do the same. Certainly the concept of a "language" doesn't fit anymore when you read this.

I think we could achieve this by adding something like I suggested [here](https://github.com/cucumber/polyglot-release/issues/56#issuecomment-1124583406) and keeping the code that's specific to this project out of the script itself.

I'm not quite sure how we'd test that though.

2022-05-15 08:57 UTC, mpkorstanje commented on polyglot-release-test
> +    POLYGLOT_RELEASE_GIT_REPO="$workdir/origin" \
I'd like to prevent the tests from potentially going online.

We could setup a dedicated git repo in the tests to represent the remote polyglot release repo.

2022-05-15 09:00 UTC, mpkorstanje commented on polyglot-release
> +  if [[ ! -f README.md ]]; then
It's a file that gets updated later on.

And we may for example change from markdown to ASCII doc. So best to check it with a clear error message.

2022-05-15 09:06 UTC, mpkorstanje commented on polyglot-release
> +SUPPORTED_LANGUAGES+=("polyglot-release")
Language is wrong, GH actions isn't a language either, it's a build system. But we have confused the two in our polyglot projects so this carries over.

We can look at making this more generic the moment we have a need for more usecases. E.g. when trying to support scala for example.

If we try to make something generic now for bash scripts we'll end up with premature assumptions.

2022-05-15 09:23 UTC, mpkorstanje commented on polyglot-release
> +SUPPORTED_LANGUAGES+=("polyglot-release")
Mmh. But maybe it's good to have a `.polyglot-release` as a 3-script build-system. Shouldn't be too difficult.

2022-05-15 10:31 UTC, mpkorstanje commented on polyglot-release
> +SUPPORTED_LANGUAGES+=("polyglot-release")
Nevermind. Way too many problems to solve. And should we get them wrong they cary beyond this repo.

This is a good feature for a separate iteration.

2022-05-16 17:12 UTC, mattwynne commented on polyglot-release-test
> +    POLYGLOT_RELEASE_GIT_REPO="$workdir/origin" \
Ah so it uses this each time it runs, to check the version is the latest one. Yeah in that case I think it makes more sense to set up a 3rd git repo in the `workdir` to simulate the `polyglot-repo` source.

Otherwise, we could have a broader `DISABLE_VERSION_CHECK` env var that we set in the tests, and unset that in the specific tests for the versioning.

2022-05-16 17:15 UTC, mattwynne commented on polyglot-release
> +  if [[ ! -f README.md ]]; then
👍 I know it's only one `if` statement but I'd prefer to test it if it's going to be there.

2022-05-16 17:18 UTC, mattwynne commented on polyglot-release
> +SUPPORTED_LANGUAGES+=("polyglot-release")
I agree in principle but my worry about refactoring this later is that once it's out in the wild with copies of the script on people's machines, it will be much harder to change it.

I'm curious to see how this would look if we'd already implemented hooks. I might give it a go in another branch just to explore it.

Shall we at least change `SUPPORTED_LANGUAGES` to be `SUPPORTED_PROJECT_TYPES` or something?

2022-05-16 17:25 UTC, mpkorstanje commented on polyglot-release
> +SUPPORTED_LANGUAGES+=("polyglot-release")
> I might give it a go in another branch just to explore it.

I'm about done with this project and it's time to ship. After this we've got our first version. Everything else we can iterate on.

Either way, we can replace the project specific code for Polyglot release with scripts. But we can't replace mistakes made with a 3-script setup once used.

Since we've only got one other project that doesn't really need it urgently a 3-script setup is not essential right now and best delayed until there is an actual usecase.

2022-05-16 17:35 UTC, mpkorstanje commented on polyglot-release
> +SUPPORTED_LANGUAGES+=("polyglot-release")
> Shall we at least change SUPPORTED_LANGUAGES to be SUPPORTED_PROJECT_TYPES or something?

No. Then we'd have to change the all the directory names in the polyglot projects too. Terms like java, javascript, ruby, are languages. The respective project types are maven, npm, rake(?).

It's better to have language that is well understood and consistent in the common usecase and slightly wrong for the exceptions.

The mismatch also makes it clear that this is not the primary usecase.

2022-05-16 23:52 UTC, mattwynne commented on polyglot-release
> +SUPPORTED_LANGUAGES+=("polyglot-release")
> > once it's out in the wild with copies of the script on people's machines, it will be much harder to change it.
> 
> Script will refuse to run if not up-to-date. 😄

Alright that makes me feel a lot better!

2022-05-17 20:07 UTC, mattwynne commented on CHANGELOG.md
> +- First release of polyglot-release
👍

2022-05-17 20:12 UTC, mattwynne requested changes
I suggest we change the `POLYGLOT_RELEASE_GIT_REPO="$workdir/origin"` line in the test runner which I think will cause confusion when we come back to this code with less context.

I think it makes sense to just disable this check for most of the tests, so I suggest making a `DISABLE_CHECK_UP_TO_DATE` env var which we set there instead, and unset it in the tests that specifically test that check.

2022-05-17 20:19 UTC, mattwynne commented on tests/check-up-to-date.sh
> +./../polyglot-release 2.0.0
Why do we need to do this in the `workdir`? Can't we just copy it into the `local` directory after we've pushed the tag? Seems like that would be more realistic.

2022-05-17 20:25 UTC, mattwynne commented on tests/created-by-contains-version.sh.expected.git-commits
> +Created-by: polyglot-release v0.0.1
Love it! :tada

2022-05-17 20:25 UTC, mattwynne commented on tests/check-up-to-date.sh
> +pushd .. > /dev/null
I think you could combine all these lines (4-12) into one clump, with a comment saying "Copy the latest version of the polyglot-release script, modified to think it's version is 0.0.1"

2022-05-21 22:00 UTC, mpkorstanje commented on tests/check-up-to-date.sh
> +./../polyglot-release 2.0.0
> Seems like that would be more realistic.

No, because the case we're guarding against is the use of an out of date `/usr/local/bin/polyglot-release`. The `./polyglot-release` version doesn't (and can't really) check itself because it hasn't been released.

2022-05-21 22:04 UTC, mpkorstanje commented
> I think it makes sense to just disable this check for most of the tests, so I suggest making a DISABLE_CHECK_UP_TO_DATE env var which we set there instead, and unset it in the tests that specifically test that check.

I think you are fundamentally misunderstanding how the up to date check works. Could you give the code in `check_up_to_date` a careful reading. Keep in mind that `POLYGLOT_RELEASE_VERSION` is only set when a release is made.

2022-05-21 22:08 UTC, mpkorstanje commented on tests/check-up-to-date.sh
> +./../polyglot-release 2.0.0
To avoid the confusion the self-reference is causing, I've changed the fixture to `ruby` instead.

2022-05-22 10:54 UTC, mpkorstanje commented
Wrote https://github.com/cucumber/polyglot-release/issues/67 to address the problem of having `polyglot-release` as a project specific implementation.

2022-05-22 10:55 UTC, merged

2022-05-22 10:56 UTC, mpkorstanje commented
Due to time constraints I've merged this because I'd like to make a release of polyglot-release and start using it to release things.

2022-05-22 22:47 UTC, aslakhellesoy commented on polyglot-release
> +      sed -i "s/^POLYGLOT_RELEASE_VERSION=.*$/POLYGLOT_RELEASE_VERSION=$NEW_VERSION/" "$file"
This won't work on a mac @mpkorstanje - the `-i` option requires an argument such as `-i ''`

2022-05-22 22:48 UTC, aslakhellesoy commented on polyglot-release
> +      sed -i "s/^POLYGLOT_RELEASE_VERSION=.*$/POLYGLOT_RELEASE_VERSION=$NEW_VERSION/" "$file"
To be portable it's better to write to a temp file and then move it.

2022-05-24 13:39 UTC, mattwynne commented
> > I think it makes sense to just disable this check for most of the tests, so I suggest making a DISABLE_CHECK_UP_TO_DATE env var which we set there instead, and unset it in the tests that specifically test that check.
> 
> I think you are fundamentally misunderstanding how the up to date check works. Could you give the code in `check_up_to_date` a careful reading.
> 
> Keep in mind that `POLYGLOT_RELEASE_VERSION` is only set when a release is made. So when released the script will always check GitHub. When not released, the script will not check GitHub. But we should always set `POLYGLOT_RELEASE_GIT_REPO` during tests to ensure that we _never_ check with GitHub, not even in case of a mistake.

OK I think I get it now - the `POLYGLOT_RELEASE_GIT_REPO` variable only has a value for the commit that's released, then we change it back to empty in the post-release commit. So in general development use it will have an empty value.

Correct?

2022-05-24 21:57 UTC, mattwynne commented
I'm easily confused!